### ISSUE TITLE
Error reconnecting to peer

### ISSUE THREAD

**Issue by KaelVNode** [mises-id/mises-tm#8]
got this log when run node

**7:42PM INF Discovering snapshots for 15s module=statesync
7:42PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
7:42PM INF Dialing peer address={"id":"40a8318fa18fa9d900f4b0d967df7b1020689fa0","ip":"18.214.250.104","port":26656} module=p2p
7:42PM INF Discovering snapshots for 15s module=statesync
7:42PM INF Dialing peer address={"id":"40a8318fa18fa9d900f4b0d967df7b1020689fa0","ip":"18.214.250.104","port":26656} module=p2p
7:43PM INF Error reconnecting to peer. Trying again addr={"id":"40a8318fa18fa9d900f4b0d967df7b1020689fa0","ip":"18.214.250.104","port":26656} err="auth failure: secret conn failed: read tcp 85.239.233.175:35888->18.214.250.104:26656: i/o timeout" module=p2p tries=3****

**Comment by freshlife001** [comment]
our seed node now had been changed

SEEDS_PEERS="1070b5c04c9b2af28aedf1b8cbeaf7e90b123464@rpc.gw.mises.site:36656"

sed -i.bak -E "s|^(seeds[[:space:]]+=[[:space:]]+).*$|\1\"$SEEDS_PEERS\"|"  ~/.misestm/config/config.toml
sed -i.bak -E "s|^(persistent_peers[[:space:]]+=[[:space:]]+).*$|\1\"\"|"  ~/.misestm/config/config.toml

**Comment by KaelVNode** [comment]
Solved
